I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 363, in script
    mc normal "I'm so tired... I stayed up all night playing otome games."#Gwyn1
  File "game/script.rpy", line 37, in char_dialogue
    if who("mc"):
NameError: name 'who' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 363, in script
    mc normal "I'm so tired... I stayed up all night playing otome games."#Gwyn1
  File "C:\Users\jtgru\OneDrive\Documents\renpy-8.1.3-sdk\renpy\ast.py", line 930, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\jtgru\OneDrive\Documents\renpy-8.1.3-sdk\renpy\exports.py", line 1474, in say
    who(what, *args, **kwargs)
  File "C:\Users\jtgru\OneDrive\Documents\renpy-8.1.3-sdk\renpy\character.py", line 1352, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "C:\Users\jtgru\OneDrive\Documents\renpy-8.1.3-sdk\renpy\character.py", line 1003, in do_display
    display_say(who,
  File "C:\Users\jtgru\OneDrive\Documents\renpy-8.1.3-sdk\renpy\character.py", line 501, in display_say
    c("begin", interact=interact, type=type, **cb_args)
  File "game/script.rpy", line 37, in char_dialogue
    if who("mc"):
NameError: name 'who' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
Gwetome Academy 1.0
Tue Feb  6 13:12:53 2024
