I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 469, in script
    $ mcname = renpy.input("What is your name?", what_outlines = dialogue_outlines)
  File "game/script.rpy", line 469, in <module>
    $ mcname = renpy.input("What is your name?", what_outlines = dialogue_outlines)
TypeError: renpy.input() got unexpected keyword argument(s): what_outlines

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 469, in script
    $ mcname = renpy.input("What is your name?", what_outlines = dialogue_outlines)
  File "C:\Users\jtgru\OneDrive\Documents\renpy-8.1.3-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\jtgru\OneDrive\Documents\renpy-8.1.3-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 469, in <module>
    $ mcname = renpy.input("What is your name?", what_outlines = dialogue_outlines)
  File "C:\Users\jtgru\OneDrive\Documents\renpy-8.1.3-sdk\renpy\exports.py", line 946, in input
    raise TypeError("renpy.input() got unexpected keyword argument(s): {}".format(", ".join(kwargs.keys())))
TypeError: renpy.input() got unexpected keyword argument(s): what_outlines

Windows-10-10.0.22631 AMD64
Ren'Py 8.1.3.23091805
Gwetome Academy 1.0
Wed May 15 10:37:59 2024
