I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 2764, in script
    mc scared "[d4] damage!" with vpunch
  File "game/script.rpy", line 2764, in <module>
    mc scared "[d4] damage!" with vpunch
NameError: name 'vp' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 2764, in script
    mc scared "[d4] damage!" with vpunch
  File "C:\Users\jtgru\OneDrive\Documents\renpy-8.1.1-sdk\renpy\ast.py", line 929, in execute
    say_menu_with(self.with_, renpy.game.interface.set_transition)
  File "C:\Users\jtgru\OneDrive\Documents\renpy-8.1.1-sdk\renpy\ast.py", line 748, in say_menu_with
    what = renpy.python.py_eval(expression)
  File "C:\Users\jtgru\OneDrive\Documents\renpy-8.1.1-sdk\renpy\python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\jtgru\OneDrive\Documents\renpy-8.1.1-sdk\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 2764, in <module>
    mc scared "[d4] damage!" with vpunch
NameError: name 'vp' is not defined

Windows-10-10.0.22631 AMD64
Ren'Py 8.1.3.23091805
Gwetome Academy 1.0
Tue Mar 12 21:59:29 2024
