I'm sorry, but an uncaught exception occurred.

While parsing C:\Users\jtgru\OneDrive\Desktop\Gwetome-Academy\game/images/Sophia/Party Night/emotions.rpy.
ScriptError: Name ('game/images/Sophia/Party/emotions.rpy', 1700892771, 413) is defined twice, at game/images/Sophia/Party Day/emotions.rpy:25 and game/images/Sophia/Party Night/emotions.rpy:25.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\jtgru\OneDrive\Documents\renpy-8.1.3-sdk\renpy\bootstrap.py", line 275, in bootstrap
    renpy.main.main()
  File "C:\Users\jtgru\OneDrive\Documents\renpy-8.1.3-sdk\renpy\main.py", line 492, in main
    renpy.game.script.load_script() # sets renpy.game.script.
  File "C:\Users\jtgru\OneDrive\Documents\renpy-8.1.3-sdk\renpy\script.py", line 310, in load_script
    self.load_appropriate_file(".rpyc", [ "_ren.py", ".rpy" ], dir, fn, initcode)
  File "C:\Users\jtgru\OneDrive\Documents\renpy-8.1.3-sdk\renpy\script.py", line 888, in load_appropriate_file
    self.finish_load(stmts, initcode, filename=lastfn) # type: ignore
  File "C:\Users\jtgru\OneDrive\Documents\renpy-8.1.3-sdk\renpy\script.py", line 525, in finish_load
    check_name(node)
  File "C:\Users\jtgru\OneDrive\Documents\renpy-8.1.3-sdk\renpy\script.py", line 501, in check_name
    raise ScriptError("Name %s is defined twice, at %s:%d and %s:%d." %
ScriptError: Name ('game/images/Sophia/Party/emotions.rpy', 1700892771, 413) is defined twice, at game/images/Sophia/Party Day/emotions.rpy:25 and game/images/Sophia/Party Night/emotions.rpy:25.

Windows-10-10.0.22631 AMD64
Ren'Py 8.1.3.23091805
 
Fri May 10 14:28:29 2024
